export function getOpenApiSpec(baseUrl: string) {
  return {
    openapi: "3.0.3",
    info: {
      title: "KodloHUB API",
      version: "1.0.0",
      description: "External API for bots and third-party integrations.",
    },
    servers: [{ url: `${baseUrl}/api/v1` }],
    security: [{ bearerAuth: [] }, { apiKeyAuth: [] }],
    components: {
      securitySchemes: {
        bearerAuth: { type: "http", scheme: "bearer", bearerFormat: "API Key" },
        apiKeyAuth: { type: "apiKey", in: "header", name: "X-API-Key" },
      },
    },
    paths: {
      "/health": { get: { summary: "Health check", security: [] } },
      "/me": { get: { summary: "Current API key info" } },
      "/stats": { get: { summary: "Site statistics" } },
      "/activity": { get: { summary: "Activity feed" } },
      "/search": { get: { summary: "Global search", parameters: [{ name: "q", in: "query", required: true }] } },
      "/posts": { get: { summary: "List posts" }, post: { summary: "Create post (write)" } },
      "/posts/{id}": { get: { summary: "Get post" } },
      "/posts/{id}/comments": { get: { summary: "Post comments" }, post: { summary: "Add comment (write)" } },
      "/profiles": { get: { summary: "List profiles" } },
      "/profiles/{id}": { get: { summary: "Get profile" } },
      "/profiles/{id}/posts": { get: { summary: "User posts" } },
      "/profiles/{id}/media": { get: { summary: "User media" } },
      "/media": { get: { summary: "List media" } },
      "/media/{id}": { get: { summary: "Get media" } },
      "/media/{id}/comments": { get: { summary: "Media comments" }, post: { summary: "Add comment (write)" } },
      "/lore": { get: { summary: "List lore" } },
      "/lore/{id}": { get: { summary: "Get lore item" } },
      "/wiki/categories": { get: { summary: "Wiki categories" } },
      "/wiki/articles": { get: { summary: "Wiki articles" }, post: { summary: "Create article (admin)" } },
      "/wiki/articles/{slug}": { get: { summary: "Get wiki article" } },
      "/wiki/articles/{slug}/revisions": { get: { summary: "Article revisions" } },
      "/podcast/episodes": { get: { summary: "Podcast episodes" }, post: { summary: "Create episode (admin)" } },
      "/podcast/settings": { get: { summary: "Podcast settings" } },
      "/games/hammer": { get: { summary: "Hammer leaderboard" } },
      "/games/nmt": { get: { summary: "NMT leaderboard" } },
      "/games/podro-clicker": { get: { summary: "Clicker leaderboard" } },
      "/games/brat-td": { get: { summary: "Brat TD leaderboard" } },
      "/og": { get: { summary: "Open Graph metadata", parameters: [{ name: "url", in: "query", required: true }] } },
      "/notifications": { post: { summary: "Send notification (write)" } },
      "/webhooks": { get: { summary: "List webhooks" }, post: { summary: "Subscribe webhook (write)" } },
      "/webhooks/{id}": { delete: { summary: "Unsubscribe webhook (write)" } },
      "/ai/slopus": { post: { summary: "Slopus AI chat" } },
      "/admin/pending-posts": { get: { summary: "Pending posts (admin)" } },
      "/admin/posts/{id}": { patch: { summary: "Moderate post (admin)" } },
      "/admin/join-requests": { get: { summary: "Join requests (admin)" } },
    },
  };
}
